project: GarbageClassification
group: VGG16
job_type: train VGG
model_type: VGG16
model_name: VGG16_reduced
model_desc: VGG16 with linear layer reduced
model_metadata:
    use_BN: true
    activation: relu
    dropout: 0.5